### PR TITLE
Issue 6 backlog

### LINKED ISSUE #25: Issue #6 Backlog
## Backlog Items ##

- [x] Adjust the filter in `List.jsx` so that spaces and upper-case letters can be used but will still find shopping list items that match even if spacing and letter case is different.

- [x] Move the conditional rendering logic in `List.jsx` from the return statement to a function.
- [x] Adjust what is returned based on whether or not the item being searched for is in the shopping list.

### PR DESCRIPTION
**Pull request by sarahmjenkins**
## Description

In `handleInput` in `List.jsx`, `.toLowerCase().trim()` moved from the end of `event.target.value` to the `.includes()` method so that the filter input would show upper-case letters and spaces.

Created a new function, `renderList`, in `List.jsx` so that the conditional statement for rendering the full list or filter list is removed from the return statement, and the return statement simply calls the function. 

Added another condition to `renderList` in `List.jsx` so that if `filterInput` has a value but `filteredList` is an empty array, a message will render that no matching items were found.

## Related Issue

Closes #25 

## Acceptance Criteria

- [x] Adjust the filter in `List.jsx` so that spaces and upper-case letters can be used but will still find shopping list items that match even if spacing and letter case is different.

 - [x] Move the conditional rendering logic in List.jsx from the return statement to a function.

- [x] Adjust what is returned based on whether or not the item being searched for is in the shopping list.

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|     | :bug: Bug fix              |
| ✓   | :sparkles: New feature     |
| ✓  | :hammer: Refactoring       |
|     | :100: Add tests            |
|     | :link: Update dependencies |
|     | :scroll: Docs              |

### Before

Note: user is unable to add spaces or capitalization to the text input.

https://user-images.githubusercontent.com/107324271/218599388-a6cbfcd7-63d1-4e11-82f3-f04b486633d3.mp4

### After

https://user-images.githubusercontent.com/107324271/218599432-f0526d86-f418-4621-8e11-f5db68c6fcbd.mp4

## Testing Steps / QA Criteria

1. Using your terminal, run the following: `git checkout main`, `git pull`, `git checkout ac-sj-issue-6-backlog`.
2. Use `npm start` to run this branch locally and test the features.
3. Navigate to the List view, and try typing in item names (varying letter case, spacing, and items that are or are not on the list).

### CODE REVIEW

**Review by alex-andria — APPROVED** [review]
Great work fixing this backlog! I think there will be some merge conflicts from the prior changes in List with the loading view. But let me know if you'd like any support on that!

**Review by djtaylor8 — APPROVED** [review]

**Review by Bustamor — COMMENTED** [review]
Nicely done! You were already on the right track.  The renderlist was great and the logic all worked out well to solve the filter issue from before.

**Review by Bustamor — APPROVED** [review]

**Review by daredtech — APPROVED** [review]

**Review by arcan9 — APPROVED** [review]
Nice work! Let's get this out of the backlog soon! lol

**Review by mtfoley — APPROVED** [review]
No need to wait on me for this.  Looks like there's a merge conflict to work out, but no doubt y'all can handle it.

**Pull request merged**
